name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Verify frontend files
        run: |
          ls -la
          test -f index.html
          test -f style.css
          test -f script.js

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=nwang2-cyber
            -Dsonar.projectKey=nwang2-cyber_ct5192-assignment2-frontend
            -Dsonar.sources=.